version: '3.7'

services:

  ytdl-subscribed:
    image: ytdl-subscribed
    build:
      context: .
    restart: unless-stopped
    environment:
      - YDL_SERVER_PROFILE=4
      - YDL_DB_PATH=/app/db/data.db
    ports:
      - 8080:8080
    volumes:
      - config:/app/db
      - video:/app/static/video
      - video:/app/downloaded

volumes:
  config:
    external: false
  video:
    external: false
